Explaining Trends in DC


```{r}
m <- leaflet(LMO) %>% 
  addTiles()  %>% 
  #addMarkers(lat = LMO$YCOORD , lng = LMO$XCOORD) %>% 
  #addCircleMarkers(lat = MetroStations$Y, lng = MetroStations$X)
  addAwesomeMarkers(lat = LMO$YCOORD , lng = LMO$XCOORD, icon = icons)
m
```


```{r}
ABC <- TrafficCount %>% filter(COUNTY == "Prince George's County" & DIR =='W')

ABC <- TrafficCount %>% group_by(COUNTY) %>% 
  summarise(GroupedVolume = sum(TotVol))

ggplot(ABC, aes(x = COUNTY, y = GroupedVolume/1000)) +
  geom_bar(stat = "identity")
```

```{r}


reg1 <- lm(TotVol~ nearest_metro_distance + DIR, data= DistanceStations)
summary(reg1)



```

```{r}

<<<<<<< HEAD


=======
lambdaValues <- 10^seq(-3, 3, length = 100)
 install.packages("caret")
library("caret")
 
 fitLasso <- train(TotVol ~ ., family='binomial', data=DistanceStations, method='glmnet', trControl=trainControl(method='cv', number=10), tuneGrid = expand.grid(alpha=1, lambda=lambdaValues))
 
 
fitElasticNet <- train(TotVol ~ ., family='binomial', data= DistanceStations, method='glmnet', trControl=trainControl(method='cv', number=10), tuneLength=10)

#Variable importance complete table
varImp(fitElasticNet)$importance %>%    # Add scale=FALSE inside VarImp if you don't want to scale
  rownames_to_column(var = "Variable") %>%
  mutate(Importance = scales::percent(Overall/100)) %>% 
  arrange(desc(Overall)) %>% 
  as_tibble()

#Variable importance plot with the most important variables
plot(varImp(fitElasticNet)) 
>>>>>>> fa638de0746b5d8d9322652c1773a555279e73d6
```

